stages:
  - staging
  - production

# before_script:
#   - eval $(ssh-agent -s)
#   - chmod 600 $SSH_PRIVATE_KEY
#   - ssh-add $SSH_PRIVATE_KEY 

deploy_staging:
  stage: staging
  script:
    - eval $(ssh-agent -s)
    - chmod 600 $SSH_PRIVATE_KEY
    - ssh-add $SSH_PRIVATE_KEY
    - ssh $USER@$APP_URL_STAGING -o StrictHostKeyChecking=no ". restart_ssh.sh && ssh-add .ssh/chatsapi && cd app && git checkout develop && git reset --hard && git pull origin develop && docker-compose down && docker-compose -f docker-compose.prod.yml up --build -d && exit"
  only:
    - develop
  tags:
    - staging

deploy_production:
  stage: production
  script:
    - eval $(ssh-agent -s)
    - chmod 600 $SSH_PRIVATE_KEY_PRODUCTION
    - ssh-add $SSH_PRIVATE_KEY_PRODUCTION
    - ssh $USER@$APP_URL_PRODUCTION -o StrictHostKeyChecking=no ". restart_ssh.sh && ssh-add .ssh/gitlab-repo && cd app && git checkout production && git reset --hard && git pull origin production && docker-compose -f docker-compose.prod.yml up --build -d && exit"
    # - ssh $USER@$APP_URL_PRODUCTION -o StrictHostKeyChecking=no ". restart_ssh.sh && ssh-add .ssh/gitlab-repo && cd app && git checkout production && git reset --hard && git pull origin production && docker-compose down && docker-compose -f docker-compose.prod.yml up --build -d && exit"
  only:
    - production
  tags:
    - production
    
